modified one line in .get_timepoints_survsummary, to round cum.n.event
kassambara/survminer pull request #445
Opened 2020-01-27 17:59 UTC by LaurenSamuels

Hi- thank you so much for this package. I added rounding in one line; you might also want to modify the line for cum.n.censor the same way.

2021-11-01 09:55 UTC, MaverickMeerkat commented
+1; Why is this not merged? This really prevents use of ggsurvplot when wanting to present cumulative number of events :-(

2021-11-01 09:56 UTC, MaverickMeerkat commented on .gitignore
> +*.swp
This seems to be not needed....

2021-11-01 09:57 UTC, MaverickMeerkat requested changes
The git ignore change is probably a mistake. Could you please undo it? 
Also you added a binary file which not sure if needed.
Maybe this is what preventing this important pull request from being approved...

2021-11-03 15:36 UTC, LaurenSamuels commented
@MaverickMeerkat , Thank you for taking a look at this. I agree that the gitignore change should not be included, but I am having trouble undoing it. Would you be able to either spell out exactly what I need to do, or just add the one useful line to .get_timepoints_survsummary another way?

2021-11-04 13:51 UTC, MaverickMeerkat commented
I opened a new pull request, because otherwise I think you would have needed to grant me permissions to change your own PR. It's here: https://github.com/kassambara/survminer/pull/564

2021-11-04 13:53 UTC, LaurenSamuels commented
Closing this request, because @MaverickMeerkat has submitted a better one (many thanks!).

2021-11-04 13:53 UTC, closed without merging